# Tmux Configuration
set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on

# Change prefix key
unbind C-b
set -g prefix C-s
bind C-s send-prefix

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Status bar configuration
set -g status on
set -g status-interval 1
set -g status-justify left
set -g status-position bottom
set -g status-left-length 50
set -g status-right-length 150
set -g status-style 'fg=#bac2de,bg=#1e1e2e'
set -g status-left '#[fg=#1e1e2e,bg=#cdd6f4,bold]  #S #[fg=#cdd6f4,bg=#313244]#[fg=#313244,bg=#1e1e2e] '
set -g status-right '#[fg=#313244,bg=#1e1e2e]#[fg=#7f849c,bg=#313244]  #(date +%%a) #[fg=#7f849c]%d %b #[fg=#45475a,bg=#313244]#[fg=#cdd6f4,bg=#45475a]  %H:%M:%S #[fg=#cdd6f4,bg=#45475a]#[fg=#1e1e2e,bg=#cdd6f4,bold]  #h '

# Window status
setw -g window-status-format '#[fg=#45475a,bg=#1e1e2e]  #I #[fg=#7f849c]#W '
setw -g window-status-current-format '#[fg=#313244,bg=#1e1e2e]#[fg=#cdd6f4,bg=#313244] #I  #[fg=#bac2de,bold]#W #[fg=#313244,bg=#1e1e2e]'
setw -g window-status-separator '#[fg=#45475a] '
setw -g window-status-current-style ''
setw -g window-status-style ''

# Pane border
set -g pane-border-style 'fg=#45475a'
set -g pane-active-border-style 'fg=#cdd6f4'

# Message text
set -g message-style 'fg=#cdd6f4,bg=#45475a'
set -g message-command-style 'fg=#cdd6f4,bg=#45475a'

# Mode style (copy mode highlight)
setw -g mode-style 'fg=#bac2de,bg=#45475a'

# Clock
setw -g clock-mode-colour '#cdd6f4'

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'

# Initialize TPM (keep this line at the very bottom of your tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# Vi mode
set-window-option -g mode-keys vi
# Keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Split windows
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"