# Wiki: https://wiki.hypr.land/Hypr-Ecosystem/hypridle/

general {
    lock_cmd = pidof hyprlock || hyprlock                                   # avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session                                # lock before suspend
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' # avoid pressing a key twice to wake the display
}

listener {
    timeout = 600                       # 10min
    on-timeout = loginctl lock-session
}

listener {
    timeout = 660                                                        # 11min
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 3600                      # 1h
    on-timeout = systemctl suspend
}
