#!/bin/bash

DIR="$HOME/.config/sketchybar/"
ITEM_DIR="$DIR/items"
PLUGIN_DIR="$DIR/plugins"

FONT="SF Pro"

source "$DIR/colors.sh"
source "$DIR/icons.sh"

# -- Bar --
sketchybar --bar \
  height=32 \
  color=$BAR_COLOR \
  position=top \
  sticky=on \
  padding_right=12 \
  padding_left=12 \
  corner_radius=0 \
  y_offset=0 \
  margin=0 \
  blur_radius=30 \
  notch_width=0

# -- Defaults --
sketchybar --default \
  icon.font="$FONT:Medium:14.0" \
  icon.color=$WHITE \
  icon.padding_left=8 \
  icon.padding_right=4 \
  label.font="$FONT:Medium:13.0" \
  label.color=$WHITE \
  label.padding_left=4 \
  label.padding_right=8 \
  background.color=$TRANSPARENT \
  background.padding_right=4 \
  background.padding_left=4

# -- LEFT --
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# -- RIGHT --
source "$ITEM_DIR/time.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/memory.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/music.sh"

sketchybar --update
