pragma Singleton

import QtQuick
import Quickshell

// Nerd Font glyphs (Font Awesome range)
Singleton {
    readonly property string play: ""
    readonly property string pause: ""
    readonly property string next: ""
    readonly property string previous: ""
    readonly property string music: ""
    readonly property string volumeHigh: ""
    readonly property string volumeLow: ""
    readonly property string volumeMute: ""
    readonly property string bell: ""
    readonly property string bellSlash: ""
    readonly property string coffee: ""
    readonly property string mic: ""
    readonly property string micSlash: ""
    readonly property string lock: ""
    readonly property string power: ""
    readonly property string moon: ""
    readonly property string reboot: ""
    readonly property string camera: ""
    readonly property string eyedropper: ""
    readonly property string terminal: ""
    readonly property string trash: ""
    readonly property string close: ""
    readonly property string record: ""
    readonly property string stop: ""
    readonly property string home: ""
    readonly property string clipboard: ""
    readonly property string sliders: ""
    readonly property string sun: ""
    readonly property string headphones: ""
    readonly property string video: ""
    readonly property string check: ""
    readonly property string search: ""
    readonly property string refresh: ""
    readonly property string speaker: ""
    readonly property string apps: ""
    readonly property string wifi: ""
    readonly property string bluetooth: ""
    readonly property string ethernet: "󰈀"
    readonly property string keyboard: ""
    readonly property string mobile: ""
    readonly property string gamepad: ""
    readonly property string desktop: ""
    readonly property string battery: ""
    readonly property string mouse: "󰍽"
    readonly property string link: ""
    readonly property string unlink: ""
    readonly property string robot: "󰚩"
    readonly property string copy: ""
    readonly property string send: ""
    readonly property string plus: ""
    readonly property string download: ""
    readonly property string cpu: "󰻠"
    readonly property string memory: "󰍛"
    readonly property string disk: "󰋊"
    readonly property string gpu: "󰢮"
    readonly property string thermometer: ""
    readonly property string arch: ""
    readonly property string wifiOff: "󰤮"
    readonly property string clock: ""
    readonly property string daySunny: ""
    readonly property string nightClear: ""
    readonly property string dayCloudy: ""
    readonly property string nightCloudy: ""
    readonly property string cloudy: ""
    readonly property string fog: ""
    readonly property string rain: ""
    readonly property string showers: ""
    readonly property string snow: ""
    readonly property string thunder: ""
    readonly property string calendar: ""
    readonly property string chevronLeft: ""
    readonly property string chevronRight: ""
    readonly property string image: ""
    readonly property string globe: ""
    readonly property string shuffle: ""
}
